spring:
  profiles:
    active: local
example:
  version: "default-v1.0"
  minimum-order-amount: 1
  support-vendors:
    - a
    - b
    - c
    - d
  description: |-
    line 1 hello world
    line 2 xxxx
    line 3

---

spring:
  config:
    activate:
      on-profile: test

example:
  version: "default-v1.0"
  minimum-order-amount: 1
  support-vendors:
    - a
    - b
    - c
    - d
  description: |-
    line 1 hello world
    line 2 xxxx
    line 3
